# Generated by Django 5.1.2 on 2024-10-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
