# Generated by Django 5.1.2 on 2024-10-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_funcionarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='NomeF',
            new_name='Nome',
        ),
    ]
